import type {Metadata} from "next";
import {geistSans, geistMono} from "@/src/components/fonts/fonts";
import "./globals.css";
import QueryClientProviderWrapper from "@/src/components/shared/QueryClientProviderWrapper";

export const metadata: Metadata = {
  title: "Muzik",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryClientProviderWrapper>
          {children}
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}