import type {Metadata} from "next";
import {geistSans, geistMono} from "@/src/components/fonts/fonts";
import "./globals.css";
import AuthProvider from "@/src/components/auth/AuthProvider";

export const metadata: Metadata = {
  title: "Muzik",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}