import type {Metadata} from "next";
import {geistSans, geistMono} from "@/components/fonts/fonts";
import "./globals.css";
import AuthProvider from "@/components/auth/AuthProvider";

export const metadata: Metadata = {
  title: "Muzik",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {

  // TODO: Add periodical refresh of the access token, should refresh a minute before expiry

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider />
      {children}
      </body>
    </html>
  );
}